#!/usr/bin/env python -tt

# Project euler, Question 2: Even Fibbonaci nos
# Each new term in Fibonnaci series is generated by adding the previous 2 terms. Starting with 1 and 2 first 10 term would be.
# 1,2,3,5,8,13,21,34,55,89,...
# By considering the terms in the Fibbonnaci series, whose values do not exceed four million, find the sub of even valued terms.
# Author: Om Prakash Singh
# Email: omps@omps.in


a = 1
b = 2

# " Generate the fibonnaci series"
